🌩 Pentest in the clouds❤️  • Clouds are a great tool to create a convenient infrastructure for applications and services. Companies and independent developers move their projects to AWS or Azure, often without thinking about security. But in vain.  • I will share with you some resources (known vulnerable laboratories) that will help pentesters,  specialists or enthusiasts, gain practical experience in searching for vulnerabilities in cloud applications deployed on Google Cloud, AWS or Azure. Resources contain practical and theoretical material: 

•  [FLAWS;](http://flaws.cloud/)
•  [FLAWS2;](http://flaws2.cloud/)
•  [CONVEX;](https://github.com/Azure/CONVEX)
•  [Sadcloud;](https://github.com/nccgroup/sadcloud)
•  [GCP Goat;](https://gcpgoat.joshuajebaraj.com/index.html)
•  [Lambhack;](https://github.com/wickett/lambhack)
•  [caponeme;](https://github.com/avishayil/caponeme)
•  [CloudGoat;](https://github.com/RhinoSecurityLabs/cloudgoat)
•  [Thunder CTF;](https://thunder-ctf.cloud/)
•  [CloudFoxable;](https://github.com/BishopFox/cloudfoxable)
•  [IAM Vulnerable;](https://github.com/BishopFox/iam-vulnerable)
•  [AWS Detonation Lab;](https://github.com/sonofagl1tch/AWSDetonationLab)
•  [OWASP WrongSecrets;](https://github.com/OWASP/wrongsecrets)
•  [OWASP ServerlessGoat;](https://github.com/OWASP/Serverless-Goat)
•  [AWS S3 CTF Challenges;](https://n0j.github.io/2017/10/02/aws-s3-ctf.html)
•  [The Big IAM Challenge by Wiz;](https://wellarchitectedlabs.com/security/)
•  [AWS Well Architected Security Labs;](https://wellarchitectedlabs.com/security/)
•  [Damn Vulnerable Cloud Application;](https://github.com/m6a-UdS/dvca)
•  [CdkGoat - Vulnerable AWS CDK Infrastructure;](https://github.com/bridgecrewio/cdkgoat)
•  [Cfngoat - Vulnerable Cloudformation Template;](https://github.com/bridgecrewio/cfngoat)
•  [TerraGoat - Vulnerable Terraform Infrastructure;](https://github.com/bridgecrewio/terragoat)
•  [AWSGoat - A Damn Vulnerable AWS Infrastructure;](https://github.com/ine-labs/AWSGoat)
•  [AzureGoat - A Damn Vulnerable Azure Infrastructure;](https://github.com/ine-labs/AWSGoat)
•  [Breaking and Pwning Apps and Servers on AWS and Azure.](https://github.com/appsecco/breaking-and-pwning-apps-and-servers-aws-azure-training)

##Join [Sicoder](https://discord.gg/mCeu84FuAy) now!